In [145]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [146]:
df = pd.read_csv('movies_metadata.csv')

In [147]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [148]:
df.shape

(45466, 24)

In [149]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [151]:
df.duplicated().sum()

np.int64(13)

In [152]:
df = df.drop_duplicates().reset_index(drop = True)

In [153]:
df.duplicated().sum()

np.int64(0)

In [154]:
df.isnull().sum()

adult                        0
belongs_to_collection    40959
budget                       0
genres                       0
homepage                 37673
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25045
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [155]:
columns_to_drop = [
    'homepage',
    'poster_path',
    'video',
    'imdb_id',
    'status',
    'budget',
    'id',
    'revenue',
    'spoken_languages',
    'title'
]

df = df.drop(columns=columns_to_drop)

In [156]:
df.isnull().sum()

adult                        0
belongs_to_collection    40959
genres                       0
original_language           11
original_title               0
overview                   954
popularity                   5
production_companies         3
production_countries         3
release_date                87
runtime                    263
tagline                  25045
vote_average                 6
vote_count                   6
dtype: int64

In [157]:
df = df.drop(columns=["belongs_to_collection" , "tagline"]) # Many missing Values

In [158]:
df.isnull().sum()

adult                     0
genres                    0
original_language        11
original_title            0
overview                954
popularity                5
production_companies      3
production_countries      3
release_date             87
runtime                 263
vote_average              6
vote_count                6
dtype: int64

In [159]:
df['overview'] = df['overview'].fillna('')

In [160]:
df.iloc[0]

adult                                                               False
genres                  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
original_language                                                      en
original_title                                                  Toy Story
overview                Led by Woody, Andy's toys live happily in his ...
popularity                                                      21.946943
production_companies       [{'name': 'Pixar Animation Studios', 'id': 3}]
production_countries    [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                   1995-10-30
runtime                                                              81.0
vote_average                                                          7.7
vote_count                                                         5415.0
Name: 0, dtype: object

In [161]:
import ast
df['genres'] = df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

In [163]:
df.iloc[0]

adult                                                               False
genres                                            Animation Comedy Family
original_language                                                      en
original_title                                                  Toy Story
overview                Led by Woody, Andy's toys live happily in his ...
popularity                                                      21.946943
production_companies       [{'name': 'Pixar Animation Studios', 'id': 3}]
production_countries    [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                   1995-10-30
runtime                                                              81.0
vote_average                                                          7.7
vote_count                                                         5415.0
Name: 0, dtype: object

In [165]:
df.iloc[0]['production_companies']

"[{'name': 'Pixar Animation Studios', 'id': 3}]"

In [166]:
import ast

def extract_companies(x):
    try:
        if pd.isna(x):
            return ""

        if isinstance(x, bool):
            return ""

        if isinstance(x, str):
            x = ast.literal_eval(x)

        return " ".join(
            item['name'].replace(" ", "_")
            for item in x
            if isinstance(item, dict) and 'name' in item
        )

    except:
        return ""

df['production_companies'] = df['production_companies'].apply(extract_companies)

In [171]:
df.iloc[1]['production_companies']

'TriStar_Pictures Teitler_Film Interscope_Communications'

In [172]:
def extract_countries(x):
    try:
        if pd.isna(x):
            return ""

        if isinstance(x, bool):
            return ""

        if isinstance(x, str):
            x = ast.literal_eval(x)

        return " ".join(
            item['name'].replace(" ", "_")
            for item in x
            if isinstance(item, dict) and 'name' in item
        )

    except:
        return ""

df['production_countries'] = df['production_countries'].apply(extract_countries)

In [173]:
df.head()

,adult,genres,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,runtime,vote_average,vote_count
0,False,Animation Comedy Family,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,Pixar_Animation_Studios,United_States_of_America,1995-10-30,81.0,7.7,5415.0
1,False,Adventure Fantasy Family,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,TriStar_Pictures Teitler_Film Interscope_Commu...,United_States_of_America,1995-12-15,104.0,6.9,2413.0
2,False,Romance Comedy,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,Warner_Bros. Lancaster_Gate,United_States_of_America,1995-12-22,101.0,6.5,92.0
3,False,Comedy Drama Romance,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,Twentieth_Century_Fox_Film_Corporation,United_States_of_America,1995-12-22,127.0,6.1,34.0
4,False,Comedy,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,Sandollar_Productions Touchstone_Pictures,United_States_of_America,1995-02-10,106.0,5.7,173.0

In [177]:
df.isnull().sum()

adult                     0
genres                    0
original_language         0
original_title            0
overview                  0
popularity                6
production_companies      0
production_countries      0
release_date             87
runtime                 263
vote_average              6
vote_count                6
dtype: int64

In [178]:
df['original_language'].fillna('unknown', inplace=True)
df['overview'].fillna('', inplace=True)

In [179]:
df['popularity'] = pd.to_numeric(df['popularity'], errors='coerce')
df['vote_average'] = pd.to_numeric(df['vote_average'], errors='coerce')
df['vote_count'] = pd.to_numeric(df['vote_count'], errors='coerce')
df['runtime'] = pd.to_numeric(df['runtime'], errors='coerce')

In [180]:
df['popularity'].fillna(df['popularity'].median(), inplace=True)
df['runtime'].fillna(df['runtime'].median(), inplace=True)
df['vote_average'].fillna(df['vote_average'].median(), inplace=True)
df['vote_count'].fillna(df['vote_count'].median(), inplace=True)

In [181]:
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')
df['release_year'] = df['release_date'].dt.year
df['release_year'].fillna(df['release_year'].median(), inplace=True)

In [182]:
df.head()

,adult,genres,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,runtime,vote_average,vote_count,release_year
0,False,Animation Comedy Family,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,Pixar_Animation_Studios,United_States_of_America,1995-10-30,81.0,7.7,5415.0,1995.0
1,False,Adventure Fantasy Family,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,TriStar_Pictures Teitler_Film Interscope_Commu...,United_States_of_America,1995-12-15,104.0,6.9,2413.0,1995.0
2,False,Romance Comedy,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.712900,Warner_Bros. Lancaster_Gate,United_States_of_America,1995-12-22,101.0,6.5,92.0,1995.0
3,False,Comedy Drama Romance,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,Twentieth_Century_Fox_Film_Corporation,United_States_of_America,1995-12-22,127.0,6.1,34.0,1995.0
4,False,Comedy,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,Sandollar_Productions Touchstone_Pictures,United_States_of_America,1995-02-10,106.0,5.7,173.0,1995.0

In [184]:
df.drop(columns=["release_date"], inplace=True)

In [185]:
df.isnull().sum()

adult                   0
genres                  0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
runtime                 0
vote_average            0
vote_count              0
release_year            0
dtype: int64

In [186]:
df['tags'] = (
    df['genres'] + ' ' +
    df['overview'] + ' ' +
    df['production_companies'] + ' ' +
    df['production_countries'] + ' ' +
    df['original_language']
)

In [188]:
df['tags'] = df['tags'].str.lower()

In [189]:
df.drop(columns=["genres" , "overview" , "production_companies" , "production_countries" , "original_language"], inplace=True)

In [190]:
df.head()

,adult,original_title,popularity,runtime,vote_average,vote_count,release_year,tags
0,False,Toy Story,21.946943,81.0,7.7,5415.0,1995.0,"animation comedy family led by woody, andy's t..."
1,False,Jumanji,17.015539,104.0,6.9,2413.0,1995.0,adventure fantasy family when siblings judy an...
2,False,Grumpier Old Men,11.712900,101.0,6.5,92.0,1995.0,romance comedy a family wedding reignites the ...
3,False,Waiting to Exhale,3.859495,127.0,6.1,34.0,1995.0,"comedy drama romance cheated on, mistreated an..."
4,False,Father of the Bride Part II,8.387519,106.0,5.7,173.0,1995.0,comedy just when george banks has recovered fr...

In [192]:
df["tags"][1]

"adventure fantasy family when siblings judy and peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite alan -- an adult who's been trapped inside the game for 26 years -- into their living room. alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. tristar_pictures teitler_film interscope_communications united_states_of_america en"

In [195]:
# nltk (Natural Language Toolkit)
# A popular Python library for NLP (Natural Language Processing).
# Used for text preprocessing, tokenization, stemming, lemmatization, stopword removal, etc.

import nltk

# stopwords
# Provides a list of common words like "the", "is", "and", "a", etc.
# These words usually don't add much meaning and are often removed before training NLP models.

from nltk.corpus import stopwords

# WordNetLemmatizer
# Converts words to their base/root form while preserving meaning.
# Example:
# "running" -> "run"
# "better" -> "good"
# "cars" -> "car"

from nltk.stem import WordNetLemmatizer

# re (Regular Expressions)
# Built-in Python library for text cleaning and pattern matching.
# Commonly used to:
# - Remove special characters
# - Remove numbers
# - Extract patterns (emails, URLs, etc.)
# Example:
# re.sub(r'[^a-zA-Z]', ' ', text)

import re

In [196]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [197]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [198]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #removed the punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split() # tokenization
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [199]:
df['tags'] = df['tags'].apply(preprocess_text)

In [200]:
df.head()

,adult,original_title,popularity,runtime,vote_average,vote_count,release_year,tags
0,False,Toy Story,21.946943,81.0,7.7,5415.0,1995.0,animation comedy family led woody andys toy li...
1,False,Jumanji,17.015539,104.0,6.9,2413.0,1995.0,adventure fantasy family sibling judy peter di...
2,False,Grumpier Old Men,11.712900,101.0,6.5,92.0,1995.0,romance comedy family wedding reignites ancien...
3,False,Waiting to Exhale,3.859495,127.0,6.1,34.0,1995.0,comedy drama romance cheated mistreated steppe...
4,False,Father of the Bride Part II,8.387519,106.0,5.7,173.0,1995.0,comedy george bank recovered daughter wedding ...

In [202]:
df = df.reset_index(drop = True)

In [206]:
indices = pd.Series(df.index,index = df['original_title']).drop_duplicates()
indices

original_title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
رگ خواب                        45448
Siglo ng Pagluluwal            45449
Betrayal                       45450
Satana likuyushchiy            45451
Queerama                       45452
Length: 45453, dtype: int64

In [207]:
from sklearn.preprocessing import MinMaxScaler

num_cols = [
    'popularity',
    'runtime',
    'vote_average',
    'vote_count',
    'release_year'
]

scaler = MinMaxScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [208]:
df.head()

,adult,original_title,popularity,runtime,vote_average,vote_count,release_year,tags
0,False,Toy Story,0.040087,0.064490,0.77,0.384725,0.828767,animation comedy family led woody andys toy li...
1,False,Jumanji,0.031079,0.082803,0.69,0.171439,0.828767,adventure fantasy family sibling judy peter di...
2,False,Grumpier Old Men,0.021394,0.080414,0.65,0.006536,0.828767,romance comedy family wedding reignites ancien...
3,False,Waiting to Exhale,0.007049,0.101115,0.61,0.002416,0.828767,comedy drama romance cheated mistreated steppe...
4,False,Father of the Bride Part II,0.015320,0.084395,0.57,0.012291,0.828767,comedy george bank recovered daughter wedding ...

In [209]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=50000 , stop_words = "english",ngram_range=(1,2))
vectors = tfidf.fit_transform(df['tags'])

In [210]:
from sklearn.metrics.pairwise import cosine_similarity
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(vectors[idx], vectors).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['original_title'].iloc[similar_idx]

In [220]:
recommend('Apollo 13')

13595    Apollo 13: To the Edge and Back
20875                 Sergeant Dead Head
2453                                Edtv
10096                     Cinderella Man
5155               First Men in the Moon
21146                      Europa Report
4097                            The Dish
18439                          Apollo 18
44339                The Mars Generation
2473                                Life
Name: original_title, dtype: object

In [225]:
import pickle

pickle.dump(vectors,open('vectors.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))